---
version: "0.6"
assignments:
  exampleAssignment: # name of an example assignment (can be any string)
    bc_length: 15
    alignment_tool:
      split_number: 1 # number of files fastq should be split for parallelization
      tool: bwa
      configs:
        min_mapping_quality: 1 # integer >=0 Please use 1 when you have oligos that differ only by 1 base.
        sequence_length: # sequence length of design excluding adapters.
          min: 166
          max: 175
        alignment_start: # start of an alignment in the reference/design_file. Here using 15 bp adapters.
          min: 1 # integer
          max: 3 # integer
    FWD:
      - resources/Assignment_BasiC/R1.fastq.gz
    BC:
      - resources/Assignment_BasiC/R2.fastq.gz
    REV:
      - resources/Assignment_BasiC/R3.fastq.gz
    design_file: resources/design.fa
    configs:
      default: {} # name of an example filtering config
